
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  # labels of deployment resource
  labels:
    app: backend
    tier:  backend
    project: expense
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
      tier:  backend
      project: expense
  template:
    metadata:
      labels:
        app: backend
        tier:  backend
        project: expense
    spec:
      containers:
        - name: backend
          image: "{{ .Values.deployment.imageURL }}:{{ .Values.Deployment.imageVersion }}"
          envFrom:
           - configMapRef:
              name: backend
